name: Create build for nginx app

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - '.github/**'
  workflow_dispatch:


jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_SECRETS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build
        env:
          DOCKERFILE: "./Dockerfile"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "nginx-repo"
          VERSION: "nginx-${{ github.sha }}"
        run: docker build -f $DOCKERFILE -t $REGISTRY/$REPOSITORY:$VERSION .

      - name: Push
        if: ${{ inputs.push }}
        env:
          DOCKERFILE: "./Dockerfile"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "nginx-repo"
          VERSION: "nginx-${{ github.sha }}"
        run: docker push $REGISTRY/$REPOSITORY:$VERSION
